### ISSUE TITLE
Lazyload datatable

### ISSUE THREAD

**Issue by Azraelir** [mmucklo/DtcGridBundle#13]
hi,

in your document, you mention:
"(warning: if your table is large, skip this example, and try the paginated datatables path below)"

does this mean that datatable by default will lazyload the data and only show portion of data?

**Comment by mmucklo** [comment]
@Azraelir sorry for the long delay in getting back to you, but my hands have been tied up for some months.

The paginated DataTables should load only the first X rows (X rows after an offset) of the data instead of the whole data set at once.

**Comment by Azraelir** [comment]
thanks.
