### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by nanawel** [mmucklo/DtcGridBundle#23]
I see there's a builtin support for "show" and "delete" actions. But how can I add new ones? The documentation is silent about that, and a quick study of the code might indicate that it's not so easy to implement.

Sources:
- https://github.com/mmucklo/DtcGridBundle/blob/symfony5/Grid/Column/ActionGridColumn.php
- https://github.com/mmucklo/DtcGridBundle/blob/176dcb54567e7f35395d6a45effb583c2c6de9ba/Util/ColumnUtil.php#L169

**Comment by mmucklo** [comment]
@nanawel

I could look into making the Action system more extensible and adding documentation.

**Comment by nanawel** [comment]
Hi @mmucklo. Thanks for your proposal.
But as stated in [my other issue](https://github.com/mmucklo/DtcGridBundle/issues/22) I had to refactor my application with SQLite and switched to https://github.com/omines/datatables-bundle that meets my needs.

**Comment by mmucklo** [comment]
Should be addressed with the latest release.
